// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopMigrationAPI.Models;

#nullable disable

namespace ShopMigrationAPI.Migrations
{
    [DbContext(typeof(ShopMigrationDbContext))]
    [Migration("20250801113932_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopMigrationAPI.Models.Category", b =>
                {
                    b.Property<int>("Categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Categoryid"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Categoryid")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Color", b =>
                {
                    b.Property<int>("Colorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("colorid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Colorid"));

                    b.Property<string>("Color1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.HasKey("Colorid")
                        .HasName("pk_color");

                    b.ToTable("color", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Contactu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_contactus");

                    b.ToTable("contactus", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Model", b =>
                {
                    b.Property<int>("Modelid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("modelid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Modelid"));

                    b.Property<string>("Model1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.HasKey("Modelid")
                        .HasName("pk_model");

                    b.ToTable("model", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.News", b =>
                {
                    b.Property<int>("Newsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("newsid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Newsid"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createddate")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("Image")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("image");

                    b.Property<string>("Shortdescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("shortdescription");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Newsid")
                        .HasName("pk_news");

                    b.HasIndex("Userid");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Order", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orderid"));

                    b.Property<string>("Customeraddress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("customeraddress");

                    b.Property<string>("Customeremail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customeremail");

                    b.Property<string>("Customername")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customername");

                    b.Property<string>("Customerphone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("customerphone");

                    b.Property<DateOnly?>("Orderdate")
                        .HasColumnType("date")
                        .HasColumnName("orderdate");

                    b.Property<string>("Ordername")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ordername");

                    b.Property<string>("Paymenttype")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymenttype");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Orderid")
                        .HasName("pk_order");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Orderdetail", b =>
                {
                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Orderid", "Productid")
                        .HasName("pk_orderdetail");

                    b.HasIndex("Productid");

                    b.ToTable("orderdetail", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Product", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Productid"));

                    b.Property<int?>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<int?>("Colorid")
                        .HasColumnType("integer")
                        .HasColumnName("colorid");

                    b.Property<string>("Image")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("image");

                    b.Property<int?>("Isnew")
                        .HasColumnType("integer")
                        .HasColumnName("isnew");

                    b.Property<int?>("Modelid")
                        .HasColumnType("integer")
                        .HasColumnName("modelid");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<string>("Productname")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("productname");

                    b.Property<DateTime?>("Sellenddate")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("sellenddate");

                    b.Property<DateTime?>("Sellstartdate")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("sellstartdate");

                    b.Property<int?>("Storageid")
                        .HasColumnType("integer")
                        .HasColumnName("storageid");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Productid")
                        .HasName("pk_product");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Colorid");

                    b.HasIndex("Modelid");

                    b.HasIndex("Storageid");

                    b.HasIndex("Userid");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Storage", b =>
                {
                    b.Property<int>("Storageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("storageid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Storageid"));

                    b.Property<string>("Storage1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("storage");

                    b.HasKey("Storageid")
                        .HasName("pk_storage");

                    b.ToTable("storage", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Userid"));

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Userid")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.News", b =>
                {
                    b.HasOne("ShopMigrationAPI.Models.User", "User")
                        .WithMany("News")
                        .HasForeignKey("Userid")
                        .HasConstraintName("fk_news_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Orderdetail", b =>
                {
                    b.HasOne("ShopMigrationAPI.Models.Order", "Order")
                        .WithMany("Orderdetails")
                        .HasForeignKey("Orderid")
                        .IsRequired()
                        .HasConstraintName("fk_orderdetail_order");

                    b.HasOne("ShopMigrationAPI.Models.Product", "Product")
                        .WithMany("Orderdetails")
                        .HasForeignKey("Productid")
                        .IsRequired()
                        .HasConstraintName("fk_orderdetail_product");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Product", b =>
                {
                    b.HasOne("ShopMigrationAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid")
                        .HasConstraintName("fk_product_category");

                    b.HasOne("ShopMigrationAPI.Models.Color", "Color")
                        .WithMany("Products")
                        .HasForeignKey("Colorid")
                        .HasConstraintName("fk_product_color");

                    b.HasOne("ShopMigrationAPI.Models.Model", "Model")
                        .WithMany("Products")
                        .HasForeignKey("Modelid")
                        .HasConstraintName("fk_product_model");

                    b.HasOne("ShopMigrationAPI.Models.Storage", "Storage")
                        .WithMany("Products")
                        .HasForeignKey("Storageid")
                        .HasConstraintName("fk_product_storage");

                    b.HasOne("ShopMigrationAPI.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("Userid")
                        .HasConstraintName("fk_product_user");

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Model");

                    b.Navigation("Storage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Color", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Model", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Order", b =>
                {
                    b.Navigation("Orderdetails");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Product", b =>
                {
                    b.Navigation("Orderdetails");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.Storage", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopMigrationAPI.Models.User", b =>
                {
                    b.Navigation("News");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
