services:
  truefeedback-api:
    image: truefeedback-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Development
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Host=truefeedback-db;Port=5432;Database=TrueFeedback;
    depends_on:
      - truefeedback-migrator
#    deploy:
#      replicas: 2
#      resources:
#        limits:
#          cpus: "0.25"
#          memory: 128M
#      restart_policy:
#        condition: on-failure
        
  truefeedback-migrator:
    image: truefeedback-migrator
    build:
      context: .
      dockerfile: Migrator.Dockerfile
      args:
        BUILD_CONFIGURATION: Development
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Host=truefeedback-db;Port=5432;Database=TrueFeedback;
    depends_on:
      - truefeedback-db
#    deploy:
#      replicas: 2
#      resources:
#        limits:
#          cpus: "0.25"
#          memory: 128M
#      restart_policy:
#        condition: none


  truefeedback-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TrueFeedback
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: "0.50"
#          memory: 256M
#      restart_policy:
#        condition: on-failure
        
  truefeedback-fe:
    image: truefeedback-fe
    ports:
      - "4200:3000"
#    deploy:
#      replicas: 2
#      resources:
#        limits:
#          cpus: "0.25"
#          memory: 128M
#      restart_policy:
#        condition: on-failure

volumes:
  db_data:
